// -*- mode: adoc -*-
= Download Cilk

The latest version of the Cilk system consists of the Tapir/LLVM
compiler and the Cheetah runtime library.  This version has
been tested on x86-64 systems running recent distributions of Linux,
including Ubuntu 18.04 and Fedora 30.

There are binary releases for two common systems (Linux/Ubuntu 18 and Mac OS) at
link:https://github.com/OpenCilk/opencilk-project/releases/tag/opencilk/beta2[OpenCilk Binary Releases]

If you want to build from source, our welcome message and build instructions are here:
link:https://github.com/OpenCilk/infrastructure/blob/release/README[OpenCilk Build Instructions]
link:https://github.com/OpenCilk/infrastructure/blob/release/INSTALLING[OpenCilk Installation Instructions]

The Tapir/LLVM compiler is the newest compiler that supports Cilk.
Tapir/LLVM extends LLVM and Clang with support for the Cilk keywords,
Cilk reducer hyperobjects, and a version of the `grainsize` pragma for
`cilk_for` loops.  The Tapir/LLVM compiler implements the Tapir
extension of LLVM's intermediate representation pass:[{% cite
SchardlMoLe17 %}] to compile task-parallel programs more efficiently
than previous compilers.  Tapir/LLVM also includes the Cilksan
determinacy-race detector, which is guaranteed to find a race if one
exists or certify the absence of races in a program execution.

The current release of the Tapir/LLVM compiler 
is based on version 9.0 of LLVM and Clang.


== Publications

pass:[{% bibliography --cited %}]
