// -*- mode: adoc -*-
= OpenCilk
// To compile this document to html5, run `asciidoc -b html5 index.txt`.
// Web page meta data.
:keywords: Cilk, Reducers, Cilksan, Cilkprof, Tapir, multicore, +
           parallel programing
:description: OpenCilk seeks to provide quality open-source +
              parallel-programming software and support services for +
              the benefit of application programmers and +
              computer-science researchers.
:page-layout: frontpage

Welcome to OpenCilk!  Here you can find recent developments with the
Cilk multithreaded programming technology.

== OpenCilk 1.0 coming soon!

// As Moore's Law comes to an end, and with it the near-automatic
// increases in computer performance provided by semiconductor
// fabrication technology, obtaining program performance from software
// will become increasingly important.  By developing the Cilk
// technology, OpenCilk aims to position Cilk as an effective open-source
// platform for next-generation multicore research.

// == News

// {% for post in site.posts limit: 5 %}
// - link:.{{ post.url }}[{{post.date | date: '%B %d, %Y' }} - {{ post.title }}]
// {% endfor %}

== What is Cilk?  What is OpenCilk?

Cilk aims to make parallel programming a simple extension of ordinary
serial programming.  Other concurrency platforms, such as
link:https://www.threadingbuildingblocks.org/[Intel's Threading
Building Blocks (TBB)] and link:http://www.openmp.org/[OpenMP], share
similar goals of making parallel programming easier.  But Cilk sets
itself apart from other concurrency platforms through its simple
link:programming[design] and link:runtime[implementation] and its
powerful suite of provably effective link:tools[tools].  These
properties make Cilk well suited as a platform for next-generation
multicore research.

OpenCilk develops and maintains *_OpenCilk_*, an open-source
implementation of the Cilk concurrency platform.  OpenCilk is largely
compatible with the link:https://www.cilkplus.org/[Cilk Plus] language
extension to C and {cpp}; see the link:programming[programming guide]
for details.  OpenCilk incorporates several enhancements to the Cilk
platform:

// link:programming[Simple language extension]:: Cilk provides a simple
// linguistic extension to the C and {cpp} programming languages that
// allows programmers to parallelize ordinary serial programs easily.

link:tapir[Compilation with Tapir/LLVM]:: OpenCilk compiles Cilk
programs using the Tapir/LLVM compiler, which is based on
link:http://llvm.org/[Clang and LLVM] and compiles parallel programs
more efficiently than existing compilers for parallel programming
languages.

link:runtime[Provably efficient scheduling]:: The Cilk runtime system
implements a work-stealing scheduler that is guaranteed to schedule
the parallel program efficiently on whatever parallel processors are
available at runtime.

link:tools[Regression testing for determinism]:: The Cilksan
determinacy-race detector, packaged with Tapir/LLVM, offers provable
guarantees that enable effective regression-testing of Cilk programs
for determinism.

link:tools[Scalability analysis]:: Cilk supports efficient tools for
finding performance bottlenecks that inhibit a program's parallel
scalability.

// link:tools[The CSI compiler-instrumentation framework]:: The
// Tapir/LLVM compiler supports CSI, a framework that allows programmers
// to develop their own dynamic-analysis tools to study Cilk program
// execution.

// Cilk reducers:: The Cilk systems supports reducer hyperobjects, a
// flexible mechanism for implementing parallel reductions.

// support parallel programming for shared-memory multicore computers.
// Cilk provides a small, stable platform for investigating and
// developing multicore computing.  Cilk software technology enables
// rapid prototyping of ideas across many research areas, including
// computer architectures, algorithms, applications, software tools,
// languages, compilers, and runtime systems.

== What's in the works?

There are several enhancements to the Cilk system currently under
development:

- New language constructs, including support for spawning statements,
  Cilk blocks that are automatically synced when control leaves their
  lexical scope, and support for inlets.
- A new implementation of reducer hyperobjects.  The new
  implementation will include an improved language syntax for using
  reducers, a more efficient implementation of reducers in the runtime
  system, and compiler optimizations that target reducers in Cilk
  programs.
- Various parallel compiler optimizations, including general sync
  elimination, fusion of `cilk_for` loops, and automatic coarsening of
  `cilk_for` loops.
- Runtime interoperability with Pthreads, to allow programmers to
  parallelize individual Pthreads using Cilk without breaking existing
  concurrency mechanisms in the program.
- Performance enhancements to the Cilksan determinacy-race detector.
  These enhancements include data-compression schemes to reduce
  Cilksan's space overhead, a more efficient implementation of the
  Cilksan algorithm, and incorporation of compiler analysis of
  determinacy races into Cilksan.
- Improved scalability analysis and profiling.  These improvements
  including augmenting Cilkscale to analyze scheduling overheads, to
  profile the work and span of a Cilk program, and to analyze the
  sensitivity of each function on the whole program's scalability.
- Integration of the CSI framework for compiler instrumentation.  The
  CSI framework makes it easy for tool writers to write efficient
  dynamic-analysis tools that use compiler instrumentation without
  modifying the compiler or understanding its internals.
- Enhanced documentation on programming in Cilk and on using each
  component of the Cilk platform.  As a result, developers working on
  other parallel languages, such as
  link:http://www.openmp.org/[OpenMP],
  link:https://julialang.org/[Julia], or
  link:https://github.com/rayon-rs/rayon[Rayon], can selectively make
  use of components of the Cilk platform, such as the Tapir/LLVM
  compiler, the runtime system, or the tool suite.
- Educational and teaching materials, workshops, and tutorials on
  Cilk.
- A cloud VM with the complete package of Cilk technologies installed
  and properly configured, to make it easy to try out Cilk.
- Cilk software libraries, including libraries for graph computations,
  such as link:https://people.eecs.berkeley.edu/~jshun/ligra.html[Ligra].
- A suite of benchmark applications written in Cilk, including
  benchmarks in the link:http://www.cs.cmu.edu/~pbbs/[Problem-based
  benchmark suite].

Have a suggestion or feature request?  We want to hear about it!
Document your suggestion as a new issue on our {issueTracker}.

== Next steps

- link:download[Download and install] the Cilk system.
- Learn how to link:programming[program] using Cilk.
- link:compiling[Compile and run] your Cilk programs using
  Tapir/LLVM.
- Read about the link:history[history] of Cilk.
- Learn about link:about[who we are].

== Contact us

Have a question about Cilk?  Want to keep up to date on the latest
Cilk technology?  Found a bug?  Have a suggestion?  Let us know!

- Report bugs and make suggestions through bugs@opencilk.org
